// src/constants/projects.ts
export const projects = [
  {
    id: 1,
    name: "PulseBoard",
    description: "Real-time anomaly detection dashboard with WebSocket integration, custom alerting system, and beautiful data visualizations.",
    tech: ["Node.js", "React", "WebSocket", "PostgreSQL", "Chart.js"],
    category: "fullstack",
    image: "/placeholder.svg?height=300&width=500",
    liveUrl: "https://pulseboard.dev",
    githubUrl: "https://github.com/devkrish/pulseboard",
    featured: true,
  },
  {
    id: 2,
    name: "TradeStreamX",
    description: "Cryptocurrency trading bot with live market signals, portfolio tracking, and automated trading strategies.",
    tech: ["Python", "FastAPI", "React", "Redis", "WebSocket"],
    category: "backend",
    image: "/placeholder.svg?height=300&width=500",
    liveUrl: "https://tradestreamx.com",
    githubUrl: "https://github.com/devkrish/tradestreamx",
    featured: true,
  },
  {
    id: 3,
    name: "ExamBoard",
    description: "Smart live examination system with real-time proctoring, automated grading, and comprehensive analytics.",
    tech: ["Node.js", "React", "MongoDB", "Socket.io", "ML"],
    category: "fullstack",
    image: "/placeholder.svg?height=300&width=500",
    liveUrl: "https://examboard.edu",
    githubUrl: "https://github.com/devkrish/examboard",
    featured: true,
  },
  {
    id: 4,
    name: "DevTools CLI",
    description: "Command-line tool for developers with project scaffolding, code generation, and deployment automation.",
    tech: ["Node.js", "TypeScript", "CLI"],
    category: "tools",
    image: "/placeholder.svg?height=300&width=500",
    liveUrl: "https://npmjs.com/devtools-cli",
    githubUrl: "https://github.com/devkrish/devtools-cli",
    featured: false,
  },
  {
    id: 5,
    name: "WeatherAPI",
    description: "RESTful API for weather data with caching, rate limiting, and comprehensive documentation.",
    tech: ["FastAPI", "Python", "Redis", "PostgreSQL"],
    category: "backend",
    image: "/placeholder.svg?height=300&width=500",
    liveUrl: "https://weatherapi.dev",
    githubUrl: "https://github.com/devkrish/weather-api",
    featured: false,
  },
  {
    id: 6,
    name: "Portfolio Generator",
    description: "React component library for generating beautiful developer portfolios with customizable themes.",
    tech: ["React", "TypeScript", "Storybook", "CSS"],
    category: "frontend",
    image: "/placeholder.svg?height=300&width=500",
    liveUrl: "https://portfolio-gen.dev",
    githubUrl: "https://github.com/devkrish/portfolio-generator",
    featured: false,
  },
];

export const categories = [
  { id: "all", name: "All Projects", count: projects.length },
  { id: "fullstack", name: "Full-Stack", count: projects.filter((p) => p.category === "fullstack").length },
  { id: "frontend", name: "Frontend", count: projects.filter((p) => p.category === "frontend").length },
  { id: "backend", name: "Backend", count: projects.filter((p) => p.category === "backend").length },
  { id: "tools", name: "Tools", count: projects.filter((p) => p.category === "tools").length },
];